<?php require('template/header.phtml'); ?>

    <div class="panel panel-default col-sm-12">
        <div class="panel-body">
            <div class="col-sm-10">
                <h2>Welcome to Social Media Magpie</h2>
                <h3>Social Isolation as a Service</h3>
                <form action="../profile.php">
                    <a class="btn btn-block btn-social btn-facebook">
                        <img src="/images/FB_F.png"/>
                    <input class="btn btn-block btn-social btn-facebook" type="submit" value="Sign in with Facebook"/>
                    </a>
                </form>
            </div>
        </div>
    </div>
