<div class="panel panel-default col-sm-12">
    <div class="panel-body">
        <div class="col-sm-10">
            <h2>Profile</h2>
            <h3>Your Tracked TV Shows</h3>

            <div id="myCarousel" class="carousel slide">
                <!-- Carousel items -->
                <div class="carousel-inner">
                    <div class="active item">
                        <img src="../images/westworld.jpg">
                        <h2>#1 Westworld</h2>
                        <div class="panel panel-default col-sm-12">
                            <h4>Friends you must avoid:</h4>
                            <p>Rick Cooper</p>
                            <p>Chris Dromey</p>
                            <p>Tim Tyler</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="../images/the-young-pope-presents-pope-banner.jpg">
                        <h2>#2 The Young Pope</h2>
                        <div class="panel panel-default col-sm-12">
                            <h4>Friends you must avoid:</h4>
                            <p>Rick Cooper</p>
                            <p>Susie Tyler</p>
                            <p>Steve Tomlinson</p>
                            <p>Gary Johnson</p>
                            <p>Becky Simcox</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="../images/The-Walking-Dead-Season-6B-Banner.jpg">
                        <h2>#3 The Walking Dead</h2>
                        <div class="panel panel-default col-sm-12">
                            <h4>Friends you must avoid:</h4>
                            <p>James Bennie</p>
                        </div>
                    </div>
                </div>
                <!-- Carousel nav -->
                <a class="carousel-control left" href="#myCarousel" data-slide="prev" role="button">&lsaquo;</a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next" role="button">&rsaquo;</a>
            </div>​

        </div>
    </div>
</div>
