    </div> <!-- End of content -->

    <div class="row">
        <div id="footer" class="col-xs-12">
		    <p>SocialMediaMagpie.TV and all other fake product and service names are trademarks of Sorry ABout The Cake Productions Limited or its
                affiliates. </p>
		    <p>Copyright &copy; 2016 SocialMediaMagpie.TV or its affiliates. All rights reserved.</p>
        </div>
    </div>
</div> <!-- End of wrapper -->
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<!--<script src="bootstrap-transition.js"></script> -->
</body>
</html>