<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="The last DVD rental website in the UK.">
    <meta name="author" content="Tim Tyler">
    <link rel="icon" href="../../images/favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <title><?php echo $view->pageTitle;?></title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="css/my-style.css" rel="stylesheet">

</head>
<?php ini_set('display_errors',0);  // Turn off error display but continue to log them.?>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../../index.php">TTDVD <img
                    src="../../images/camera.png" width='42' height='35'
                    onmouseover="this.src='../../images/camera_light.png';"
                    onmouseout="this.src='../../images/camera.png';"/>
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown active">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filter Movies<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Filter Movies</li>
                        <li class=""><a href="../../show_all_movies.php">Show All Movies</a></li>
                        <li class=""><a href="../../show_family_movies.php">Show Family Movies</a></li>
                        <li class=""><a href="../../search_for_movie.php">Search For Movie</a></li>
                        <li class=""><a href="../../filter_by_genre.php">Filter By Genre</a></li>
                        <li class=""><a href="../../filter_by_director.php">Filter By Director</a></li>
                        <li class=""><a href="../../filter_by_actor.php">Filter By Actor</a></li>
                    </ul>
                </li>

                <?php if (isset($_SESSION['member'])) { ?>
                    <li><a href="../../login.php"><?php
                            echo "Member's Area (logged in as " . $_SESSION['member']->getFirstName() . ")"; ?></a>
                    <li class=""><a href="/basket.php">My Basket<img src="../../images/basket.png"/></a></li><?php
                } else { ?>
                    <li><a href="../../login.php">Login</a></li><?php
                }?>
                <li>
                    <div class="pull-right">
                        <br>
                        <form action="search_for_movie.php" method="post">
                            <input type="text" name="advanced_search" value="" class="input_box">
                            <input class="" type="submit" value="Search" name="submit" class="btn btn-primary"/>
                        </form>
                    </div>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>


<div id="wrapper" class="col-xs-12">
    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
    </div>
    <div id="content" class="col-xs-8 "><br><br><br>