<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="The last DVD rental website in the UK.">
    <meta name="author" content="Tim Tyler">
    <link rel="icon" href="../../images/favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <title><?php echo $view->pageTitle;?></title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-social.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/my-style.css" rel="stylesheet">

</head>
<?php //ini_set('display_errors',0);  // Turn off error display but continue to log them.?>
<body>



<div id="wrapper" class="col-xs-12">
    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
    </div>
    <div id="content" class="col-xs-8 "><br><br><br>